/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact { 'number' : string, 'contactLabel' : string }
export interface Tshirt {
  'deliveryCharge' : string,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'imageKey' : string,
  'colors' : Array<string>,
  'price' : string,
}
export interface UserProfile { 'name' : string }
export interface _SERVICE {
  'addContact' : ActorMethod<[Contact], undefined>,
  'addTshirt' : ActorMethod<[Tshirt], undefined>,
  'getAllTshirts' : ActorMethod<[], Array<Tshirt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getPaymentQR' : ActorMethod<[], Uint8Array>,
  'getTshirt' : ActorMethod<[string], Tshirt>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsappNumber' : ActorMethod<[], string>,
  'removeContact' : ActorMethod<[string], undefined>,
  'removeTshirt' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTshirts' : ActorMethod<[string], Array<Tshirt>>,
  'setPaymentQR' : ActorMethod<[Uint8Array], undefined>,
  'setWhatsappNumber' : ActorMethod<[string], undefined>,
  'updateTshirt' : ActorMethod<[Tshirt], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];