/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Contact = IDL.Record({
  'number' : IDL.Text,
  'contactLabel' : IDL.Text,
});
export const Tshirt = IDL.Record({
  'deliveryCharge' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'imageKey' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  'addContact' : IDL.Func([Contact], [], []),
  'addTshirt' : IDL.Func([Tshirt], [], []),
  'detectUserCurrency' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllTshirts' : IDL.Func([], [IDL.Vec(Tshirt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCurrencyRates' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPaymentQR' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
  'getRatesCachedAt' : IDL.Func([], [IDL.Int], ['query']),
  'getTshirt' : IDL.Func([IDL.Text], [Tshirt], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
  'refreshExchangeRates' : IDL.Func([], [IDL.Text], []),
  'removeContact' : IDL.Func([IDL.Text], [], []),
  'removeTshirt' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTshirts' : IDL.Func([IDL.Text], [IDL.Vec(Tshirt)], ['query']),
  'setPaymentQR' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
  'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
  'updateTshirt' : IDL.Func([Tshirt], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Contact = IDL.Record({
    'number' : IDL.Text,
    'contactLabel' : IDL.Text,
  });
  const Tshirt = IDL.Record({
    'deliveryCharge' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'imageKey' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    'addContact' : IDL.Func([Contact], [], []),
    'addTshirt' : IDL.Func([Tshirt], [], []),
    'detectUserCurrency' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllTshirts' : IDL.Func([], [IDL.Vec(Tshirt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCurrencyRates' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPaymentQR' : IDL.Func([], [IDL.Vec(IDL.Nat8)], ['query']),
    'getRatesCachedAt' : IDL.Func([], [IDL.Int], ['query']),
    'getTshirt' : IDL.Func([IDL.Text], [Tshirt], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
    'refreshExchangeRates' : IDL.Func([], [IDL.Text], []),
    'removeContact' : IDL.Func([IDL.Text], [], []),
    'removeTshirt' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTshirts' : IDL.Func([IDL.Text], [IDL.Vec(Tshirt)], ['query']),
    'setPaymentQR' : IDL.Func([IDL.Vec(IDL.Nat8)], [], []),
    'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
    'updateTshirt' : IDL.Func([Tshirt], [], []),
  });
};

export const init = ({ IDL }) => { return []; };