/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact { 'number' : string, 'contactLabel' : string }
export type ExternalBlob = Uint8Array;
export interface Tshirt {
  'deliveryCharge' : string,
  'name' : string,
  'description' : string,
  'sizes' : Array<string>,
  'stock' : bigint,
  'imageKey' : string,
  'colors' : Array<string>,
  'price' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[Contact], undefined>,
  'addTshirt' : ActorMethod<[Tshirt], undefined>,
  'updateTshirt' : ActorMethod<[Tshirt], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllTshirts' : ActorMethod<[], Array<Tshirt>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getPaymentQR' : ActorMethod<[], ExternalBlob>,
  'getTshirt' : ActorMethod<[string], Tshirt>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWhatsappNumber' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeContact' : ActorMethod<[string], undefined>,
  'removeTshirt' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTshirts' : ActorMethod<[string], Array<Tshirt>>,
  'setPaymentQR' : ActorMethod<[ExternalBlob], undefined>,
  'setWhatsappNumber' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];