/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Contact = IDL.Record({
  'number' : IDL.Text,
  'contactLabel' : IDL.Text,
});
export const Tshirt = IDL.Record({
  'deliveryCharge' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(IDL.Text),
  'stock' : IDL.Nat,
  'imageKey' : IDL.Text,
  'colors' : IDL.Vec(IDL.Text),
  'price' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([Contact], [], []),
  'addTshirt' : IDL.Func([Tshirt], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllTshirts' : IDL.Func([], [IDL.Vec(Tshirt)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getPaymentQR' : IDL.Func([], [ExternalBlob], ['query']),
  'getTshirt' : IDL.Func([IDL.Text], [Tshirt], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeContact' : IDL.Func([IDL.Text], [], []),
  'removeTshirt' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTshirts' : IDL.Func([IDL.Text], [IDL.Vec(Tshirt)], ['query']),
  'setPaymentQR' : IDL.Func([ExternalBlob], [], []),
  'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Contact = IDL.Record({
    'number' : IDL.Text,
    'contactLabel' : IDL.Text,
  });
  const Tshirt = IDL.Record({
    'deliveryCharge' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(IDL.Text),
    'stock' : IDL.Nat,
    'imageKey' : IDL.Text,
    'colors' : IDL.Vec(IDL.Text),
    'price' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([Contact], [], []),
    'addTshirt' : IDL.Func([Tshirt], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllTshirts' : IDL.Func([], [IDL.Vec(Tshirt)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getPaymentQR' : IDL.Func([], [ExternalBlob], ['query']),
    'getTshirt' : IDL.Func([IDL.Text], [Tshirt], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWhatsappNumber' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeContact' : IDL.Func([IDL.Text], [], []),
    'removeTshirt' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTshirts' : IDL.Func([IDL.Text], [IDL.Vec(Tshirt)], ['query']),
    'setPaymentQR' : IDL.Func([ExternalBlob], [], []),
    'setWhatsappNumber' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };