/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Tshirt {
    deliveryCharge: string;
    name: string;
    description: string;
    sizes: Array<string>;
    stock: bigint;
    imageKey: string;
    colors: Array<string>;
    price: string;
}
export interface Contact {
    number: string;
    contactLabel: string;
}
export interface UserProfile {
    name: string;
}
export interface backendInterface {
    addContact(contact: Contact): Promise<void>;
    addTshirt(tshirt: Tshirt): Promise<void>;
    detectUserCurrency(userIp: string): Promise<string>;
    getAllTshirts(): Promise<Array<Tshirt>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getContacts(): Promise<Array<Contact>>;
    getCurrencyRates(): Promise<string | null>;
    getPaymentQR(): Promise<Uint8Array>;
    getRatesCachedAt(): Promise<bigint>;
    getTshirt(name: string): Promise<Tshirt>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWhatsappNumber(): Promise<string>;
    refreshExchangeRates(): Promise<string>;
    removeContact(contactLabel: string): Promise<void>;
    removeTshirt(name: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTshirts(term: string): Promise<Array<Tshirt>>;
    setPaymentQR(blob: Uint8Array): Promise<void>;
    setWhatsappNumber(number: string): Promise<void>;
    updateTshirt(tshirt: Tshirt): Promise<void>;
}
import type { UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContact(arg0: Contact): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0);
            return result;
        }
    }
    async addTshirt(arg0: Tshirt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTshirt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTshirt(arg0);
            return result;
        }
    }
    async detectUserCurrency(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.detectUserCurrency(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.detectUserCurrency(arg0);
            return result;
        }
    }
    async getAllTshirts(): Promise<Array<Tshirt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTshirts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTshirts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getCurrencyRates(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrencyRates();
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrencyRates();
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaymentQR(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentQR();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentQR();
            return result;
        }
    }
    async getRatesCachedAt(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatesCachedAt();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatesCachedAt();
            return result;
        }
    }
    async getTshirt(arg0: string): Promise<Tshirt> {
        if (this.processError) {
            try {
                const result = await this.actor.getTshirt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTshirt(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWhatsappNumber(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getWhatsappNumber();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWhatsappNumber();
            return result;
        }
    }
    async refreshExchangeRates(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.refreshExchangeRates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.refreshExchangeRates();
            return result;
        }
    }
    async removeContact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeContact(arg0);
            return result;
        }
    }
    async removeTshirt(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTshirt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTshirt(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchTshirts(arg0: string): Promise<Array<Tshirt>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTshirts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTshirts(arg0);
            return result;
        }
    }
    async setPaymentQR(arg0: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentQR(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentQR(arg0);
            return result;
        }
    }
    async setWhatsappNumber(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setWhatsappNumber(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setWhatsappNumber(arg0);
            return result;
        }
    }
    async updateTshirt(arg0: Tshirt): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTshirt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTshirt(arg0);
            return result;
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
